"use strict";

const { write } = require("./files");
const path = require("path");

/**
 * Generates a CHECKLIST.md — must-pass checks before merging any PR.
 * Also writes a .github/pull_request_template.md so it shows up on every PR.
 */
function generateChecklist(root, name, opts) {
    const md = `# ✅ Pre-Merge Checklist — ${name}

> Every item below must be checked before merging a pull request.
> This ensures the project stays in a standard, pragmatic, production-ready state.

---

## 🧹 Code Quality

- [ ] No commented-out code (run \`npx eslint ./src --fix\` to auto-remove)
- [ ] No unused imports or variables
- [ ] No \`console.log\` left in production code (use a logger or remove)
- [ ] No \`TODO\` comments left unresolved in the diff
- [ ] No hardcoded secrets, API keys, or credentials in code
- [ ] All environment variables are documented in \`.env.example\`

---

## 🏗️ Structure & Standards

- [ ] New components are placed in the correct folder (\`src/components/ui/\` for primitives, \`src/components/\` for feature components)
- [ ] New pages follow the correct structure for the stack (App Router folders for Next.js, \`src/pages/\` for React)
- [ ] No business logic inside UI components — logic belongs in hooks or services
- [ ] No direct API calls inside components — use \`src/services/api.ts\`
- [ ] TypeScript types defined in \`src/types/\` — no \`any\` types without justification
- [ ] Constants live in \`src/constants/\` — no magic numbers or strings in components
${opts.firebase ? `- [ ] Firestore reads use the typed converter from \`src/lib/firebase/converters.ts\`\n- [ ] Firebase errors use \`getFirebaseErrorMessage()\` from \`src/lib/firebase/errors.ts\`` : ""}

---

## 🎨 UI & Styling

${opts.shadcn ? `- [ ] UI primitives use shadcn/ui components — not custom-built equivalents
- [ ] Icons use Lucide React — no other icon libraries introduced
- [ ] Font is Geist — no other fonts added without approval` : `- [ ] Tailwind utility classes used consistently — no inline styles mixed in`}
- [ ] All interactive elements have hover and focus states
- [ ] UI is responsive — tested on mobile and desktop
- [ ] No hardcoded colours — use Tailwind theme tokens or CSS variables
- [ ] Loading states handled for all async operations
- [ ] Error states handled and displayed to the user

---

## 🔒 Security

- [ ] No sensitive data exposed in the frontend (no private keys, no admin credentials)
- [ ] User input is validated before sending to the backend
- [ ] Authentication checks in place for protected routes
${opts.firebase ? `- [ ] Firestore security rules updated if new collections were added` : ""}

---

## ⚡ Performance

- [ ] No unnecessary re-renders (check with React DevTools if needed)
- [ ] Images optimised${opts.stack === "next" ? ` and using Next.js \`<Image />\` component` : ""}
- [ ] No large dependencies added without justification (check bundle size)
- [ ] Lazy loading used for heavy components or pages where applicable

---

## 🧪 Testing

- [ ] Feature works as expected in the browser
- [ ] Edge cases tested (empty states, error states, loading states)
- [ ] No regressions introduced in existing features

---

## 📝 Documentation

- [ ] \`README.md\` updated if new setup steps are required
- [ ] New environment variables added to \`.env.example\`
- [ ] Complex logic has a brief comment explaining the why (not the what)

---

## 🚀 Before Merging

- [ ] Branch is up to date with \`main\`
- [ ] All ESLint warnings resolved (\`npm run lint\`)
- [ ] Build passes without errors (\`npm run build\`)
- [ ] No merge conflicts

---

*Generated by [create-em-app](https://github.com/Youngemmy5956/create-em-app)*
`;

    write(path.join(root, "CHECKLIST.md"), md);

    // Also write GitHub PR template so checklist appears on every PR automatically
    write(path.join(root, ".github/pull_request_template.md"), `## What does this PR do?

<!-- Brief description of the changes -->

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Docs update
- [ ] Other: ___

## Pre-Merge Checklist

> Copy from CHECKLIST.md and tick off each item before requesting a review.

- [ ] No commented-out code
- [ ] No unused imports or variables
- [ ] No hardcoded secrets or API keys
- [ ] Components in correct folders
- [ ] No \`any\` types without justification
- [ ] UI is responsive
- [ ] Loading and error states handled
- [ ] Build passes: \`npm run build\`
- [ ] Lint passes: \`npm run lint\`
- [ ] Branch is up to date with \`main\`

## Screenshots (if UI change)

<!-- Add before/after screenshots here -->
`);
}

module.exports = { generateChecklist };